services:
  python:
    build: .
    tty: true
    stdin_open: true
    depends_on:
      - timescaledb
    volumes:
      - ./logs:/logs
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password