
volumes:
  tsdb_data:
  certbot:

services:

  dhtlogger:
    container_name: pi-humidity-dhtlogger
    image: haydeni0/pi-humidity:python
    tty: true
    stdin_open: true
    depends_on:
      - timescaledb
    volumes:
      - ./src:/src
      - ./shared:/shared
    entrypoint: ["python", "-u", "/src/dhtLogger.py"]
    env_file:
      - postgres.env
      - password.env
    devices:
      # Access to GPIO pins (https://stackoverflow.com/a/48234752)
      - /dev/gpiomem
    restart: always

  dhtplotter:
    container_name: pi-humidity-dhtplotter
    image: haydeni0/pi-humidity:python
    tty: true
    stdin_open: true
    depends_on:
      - timescaledb
    volumes:
      - ./src:/src
      - ./shared:/shared
      - certbot:/etc/letsencrypt
    env_file:
      - postgres.env
      - password.env
      - webserver.env
    restart: always
    ports:
      - 80:80
      - 443:443
    entrypoint: ["python", "/src/dhtPlotter.py"]

  testplotter:
    container_name: pi-humidity-testplotter
    image: haydeni0/pi-humidity:python
    tty: true
    stdin_open: true
    depends_on:
      - timescaledb
    volumes:
      - ./src:/src
      - ./shared:/shared
    env_file:
      - postgres.env
      - password.env
    restart: always
    ports:
      - 8080:80
      - 8443:443
    # entrypoint: ["python", "/src/dhtPlotter.py"]

  timescaledb:
    container_name: pi-humidity-timescaledb
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    volumes:
      - tsdb_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
      - password.env
    restart: always

