services:
  dhtlogger:
    build: .
    depends_on:
      - timescaledb
    volumes:
      - ./logs:/logs
      - ./src:/src
    entrypoint: python -u "/src/testLogger.py"
    env_file:
      - postgres.env
      - password.env
      # devices:
      # Access to GPIO pins (https://stackoverflow.com/a/48234752)
      # - /dev/gpiomem
    restart: always
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - postgres.env
      - password.env
  # pgadmin:
  #   image: dpage/pgadmin4:6.15 #amd64
  #   image: hunnguye/pgadmin4-armv7:6.14 #arm/v7
