name: pi-humidity
channels:
  - defaults
  - plotly
dependencies:
  - python=3.10
  - pip
  - numpy=1.23
  - pandas
  - matplotlib
  - plotly=5.11.0
  - black
  - pip:
      - psycopg2-binary
      - adafruit_DHT==1.4.0 --install-option='--force-pi'
      - dash
